export const DISPLAY_ALERT = 'DISPLAY_ALERT'
// Auth
export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const UPDATE_USER = 'UPDATE_USER'
// Study Questions
export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS'
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'
export const CREATE_QUESTION = 'CREATE_QUESTION'
export const UPDATE_QUESTION = 'UPDATE_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION'
