name: Cypress Tests

on:
  push:
    branches: [development]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create .env file
        run: |
          touch .env
          echo PORT="${{ secrets.PORT }}" >> .env
          echo MONGO_URL="${{ secrets.MONGO_URL }}" >> .env
          echo JWT_SECRET="${{ secrets.JWT_SECRET }}" >> .env
          echo JWT_LIFETIME="${{ secrets.JWT_LIFETIME }}" >> .env
          ls
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
      
      - name: Install dependencies
        run: npm install
        
      - name: Start application
        run: npm start

      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          working-directory: frontend
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          headless: true
